USE DELIVERY_PIZZA
GO

/*>>>--CREACIÓN DE VISTAS--<<<*/
--1º VISTA DEL NÚMERO DE ORDEN + FECHA DE EMISIÓN, CON EL NOMBRE COMPLETO DEL CLIENTE + DNI Y EL NOMBRE COMPLETO DEL REPARTIDOR DE LA ORDEN + BREVETE
CREATE VIEW V_EMPLEADOS_CLIENTES_ORDEN
AS
	SELECT
		[NÚMERO DE ORDEN]				= ORD.NUM_ORDEN,
		[FECHA]							= ORD.FECHA,
		[NOMBRE COMPLETO DEL CLIENTE]	= CLI.NOMBRE + ' ' + CLI.APELLIDOS,
		[DNI DEL CLIENTE]				= CLI.DNI,
		[NOMBRE COMPLETO REPARTIDOR]	= EMP.NOMBRE + ' ' + EMP.APELLIDOS,
		[BREVETE DE REPARTIDOR]			= REP.NUM_BREVETE
	FROM ORDEN AS ORD
		INNER JOIN CLIENTE		AS CLI ON ORD.ID_CLIENTE	= CLI.ID_CLIENTE
		INNER JOIN REPARTIDOR	AS REP ON ORD.ID_EMPLEADO	= REP.ID_EMPLEADO
		INNER JOIN EMPLEADO		AS EMP ON REP.ID_EMPLEADO	= EMP.ID_EMPLEADO
GO
SELECT * FROM DBO.V_EMPLEADOS_CLIENTES_ORDEN 
GO

--2º VISTA DE LA FECHA DEL PROCESO ELABORACIÓN LOS EMPLEADOS QUE INTERVINIERON + CARGO DE EMPLEADO Y EL HORNO EMPLEADO + TIPO DE HORNO
CREATE VIEW V_INFO_ELAB_EMP
AS
	SELECT
		[FECHA DE ELABORACION]		= ELA.FECHA,
		[NOMBRE COMPLETO EMPLEADO]	= EMP.NOMBRE + ' ' + EMP.APELLIDOS,
		[COD DE HORNO]				= ELA.ID_HORNO,
		CASE HOR.TIPO_HORNO 
			WHEN 'LEÑ' THEN 'LEÑA'
			WHEN 'ART' THEN 'ARTESANAL'
			ELSE 'ELECTRICO'
		END AS [TIPO DE HORNO]
	FROM ELABORACION AS ELA
		INNER JOIN EMPLEADO AS EMP ON ELA.ID_EMPLEADO	= EMP.ID_EMPLEADO
		INNER JOIN HORNO	AS HOR ON ELA.ID_HORNO		= HOR.ID_HORNO
GO
SELECT * FROM V_INFO_ELAB_EMP
GO

--3º VISTA DE EMPLEADOS QUE TRABAJARON EN UNA ORDEN DE UN CLIENTE + LA FECHA
CREATE VIEW V_CONSULTA_ORDEN
AS
	SELECT
		[NRO DE ORDEN]					= ORD.NUM_ORDEN,
		[NOMBRE CLIENTE]				= CLI.NOMBRE,
		[NOMBRE COMPLETO DE EMPLEADO]	= EMP.NOMBRE + ' ' + EMP.APELLIDOS,
		[FECHA DE ORDEN]				= ORD.FECHA
	FROM ORDEN AS ORD
		INNER JOIN CLIENTE	AS CLI ON ORD.ID_CLIENTE	= CLI.ID_CLIENTE
		INNER JOIN EMPLEADO AS EMP ON EMP.ID_EMPLEADO	= EMP.ID_EMPLEADO 
GO
SELECT * FROM DBO.V_CONSULTA_ORDEN
GO

--4º VISTA
CREATE VIEW V_EMPLEADOS_COCINA_DETALLE
AS
	SELECT  
		[DNI EMPLEADO] = E.DNI, 
		[EDAD EMPLEADO] = E.EDAD, 
		[NOMBRE COMPLETO EMPLEADO] = E.NOMBRE + ' ' + E.APELLIDOS,
		CASE EC.CARGO 
			WHEN 'MAS' THEN 'MAESTRO PIZZERO'
			ELSE 'AYUDANTE DE PIZZERO'
		END AS [CARGO EMPLEADO],
		[TELÉFONO EMPLEADO] = E.TELEFONO,
		[CANTIDAD DE ELABORACIONES HECHAS] = ELA.CANTIDAD
	FROM EMPLEADO_COCINA EC
		INNER JOIN EMPLEADO		AS E ON EC.ID_EMPLEADO = E.ID_EMPLEADO
		INNER JOIN ELAB_PIZZA	AS ELA ON E.ID_EMPLEADO=ELA.ID_EMPLEADO
GO
SELECT * FROM V_EMPLEADOS_COCINA_DETALLE
GO

--5º VISTA
CREATE VIEW V_DE_PIZZA_L
AS
      SELECT 
	      [CODÍGO DE PIZZA] = PIX.COD_PIZZA,
		  [SABOR PIZZA]		= PIX.SABOR_PIZZA,
		  [PRECIO]			= PIX.PRECIO,
		  [CANTIDAD]		= ELP.CANTIDAD,
		  [FECHA]			= HOR.FECHA_COMPRA
	  FROM PIZZA AS PIX
		  INNER JOIN ELAB_PIZZA AS ELP ON PIX.COD_PIZZA = ELP.COD_PIZZA
		  INNER JOIN HORNO		AS HOR ON ELP.ID_HORNO = HOR.ID_HORNO
GO
SELECT * FROM DBO.V_DE_PIZZA_L
GO


/*>>>--CREACIÓN DE PROCEDURES--<<<*/
/*PROCEDURE CONSULTAS*/

--PROC CONSULTA 1
CREATE PROCEDURE USP_CONSULTA_VISTA_1
	@NOMBRE_CLI		VARCHAR(50),
	@APELLIDOS_CLI	VARCHAR(50),
	@DNI_CLI		CHAR(8)
AS
	BEGIN
		SELECT
			[NÚMERO DE ORDEN]				= VIS1.[NÚMERO DE ORDEN],
			[FECHA]							= VIS1.[FECHA],
			[NOMBRE COMPLETO REPARTIDOR]	= VIS1.[NOMBRE COMPLETO REPARTIDOR],
			[BREVETE DE REPARTIDOR]			= VIS1.[BREVETE DE REPARTIDOR]
		FROM V_EMPLEADOS_CLIENTES_ORDEN AS VIS1
			INNER JOIN CLIENTE AS CLI ON VIS1.[NOMBRE COMPLETO DEL CLIENTE]	= CLI.NOMBRE + ' ' + CLI.APELLIDOS
		WHERE CLI.NOMBRE = @NOMBRE_CLI
				AND CLI.APELLIDOS = @APELLIDOS_CLI
				AND CLI.DNI = @DNI_CLI
	END
GO
EXEC USP_CONSULTA_VISTA_1 'ANDREA', 'HUASACA CHUKISUTA', '71354678'
GO

--PROC CONSULTA 2
CREATE PROC USP_CONSULTA_HORNO
	@NOMEMP VARCHAR(20),
	@APEEMP VARCHAR(30)
AS
BEGIN
		SELECT
		[FECHA DE ELABORACION]	= ELA.FECHA,
		[NOMBRES]				= EMP.NOMBRE + ', ' + EMP.APELLIDOS,
		[COD DE HORNO]			= ELA.ID_HORNO,
		[TIPO DE HORNO]			= HOR.TIPO_HORNO
	FROM ELABORACION AS ELA
		INNER JOIN EMPLEADO AS EMP ON ELA.ID_EMPLEADO = EMP.ID_EMPLEADO
		INNER JOIN HORNO AS HOR ON ELA.ID_HORNO = HOR.ID_HORNO
		WHERE EMP.NOMBRE = @NOMEMP 
			AND EMP.APELLIDOS = @APEEMP
END
GO
EXEC USP_CONSULTA_HORNO 'BENITO','CAMELAS SALAS'
GO

--PROC CONSULTA 3
CREATE PROCEDURE CONSULTAPROC
@NRO_ORDEN CHAR(5),
@ID_CLIENTE CHAR(6)
AS
BEGIN 
	SELECT
		[NRO DE ORDEN]		= ORD.NUM_ORDEN,
		[ID DE CLIENTE]		= CLI.ID_CLIENTE,
		[ID EMPLEADO]		= EMP.ID_EMPLEADO,
		[FECHA DE ORDEN]	= ORD.FECHA
	FROM ORDEN AS ORD
		INNER JOIN CLIENTE	AS CLI ON ORD.ID_CLIENTE	= CLI.ID_CLIENTE
		INNER JOIN EMPLEADO AS EMP ON EMP.ID_EMPLEADO	= EMP.ID_EMPLEADO
	WHERE CLI.ID_CLIENTE = @ID_CLIENTE 
		AND ORD.NUM_ORDEN= @NRO_ORDEN
END
GO
EXEC CONSULTAPROC 'N-001', 'CL-008'
GO

--PROC CONSULTA 4
CREATE PROCEDURE SP_DE_PIZZA
     @ID_HORNO CHAR (6)
AS
BEGIN
     SELECT 
      PIX.SABOR_PIZZA, PIX.PRECIO, PIX.COD_PIZZA, ELP.CANTIDAD
FROM PIZZA AS PIX
      INNER JOIN ELAB_PIZZA AS ELP ON PIX.COD_PIZZA = ELP.COD_PIZZA
WHERE
      PIX.COD_PIZZA IN(SELECT COD_PIZZA FROM ELAB_PIZZA
						WHERE ID_HORNO =  @ID_HORNO)
		AND PIX.PRECIO > 40
END
GO
EXEC dbo.SP_DE_PIZZA 'HO-005'
GO

--PROC CONSULTA 5
CREATE PROCEDURE sp_union_OrdenPizza_Pizza
AS
BEGIN
	SELECT 
	ord.COD_PIZZA as [Codigo Pizza],
	piz.SABOR_PIZZA as Sabor,
	piz.PRECIO as Precio
	from ORDEN_PIZZA as Ord 
	inner join Pizza as Piz on Ord.COD_PIZZA=Piz.COD_PIZZA
END
GO
EXEC sp_union_OrdenPizza_Pizza
GO


/*PROCEDURE DML*/

--PROC DML 1
CREATE PROCEDURE USP_DML_INSERCION
	@ID_CLIEN	CHAR(6), 
	@DNI		CHAR(8), 
	@NOMBRE		VARCHAR(20), 
	@APELLIDOS	VARCHAR(30), 
	@DIRECCION	VARCHAR(45), 
	@TELEFONO	VARCHAR(9)
AS
	BEGIN
		IF EXISTS (SELECT * FROM CLIENTE AS CLI WHERE CLI.ID_CLIENTE = @ID_CLIEN)
			BEGIN
				PRINT 'CÓDIGO DE CLIENTE INCORRECTO, EL CÓDIGO YA EXISTE'
			END
		ELSE
			BEGIN
				INSERT INTO CLIENTE VALUES (@ID_CLIEN, @DNI, @NOMBRE, @APELLIDOS, @DIRECCION, @TELEFONO)
			END
	END
GO
EXEC USP_DML_INSERCION 'CL-015', '77777798', 'ELMA', 'MARRANO DOSANTOS', 'JR. BRIGADA VIRACOCHA', '98888089'
GO

--PROC DML 2
CREATE PROC USP_INSERT_DATOS
	@IDHORNO1	CHAR(6),
	@TIPHORNO	VARCHAR(9),
	@FECOMPRA	DATE
AS
BEGIN
	IF EXISTS (SELECT * FROM HORNO AS HOR WHERE HOR.ID_HORNO = @IDHORNO1)
			BEGIN
				PRINT 'CÓDIGO DE HORNO INCORRECTO, EL CÓDIGO YA EXISTE'
			END
	ELSE
			BEGIN
				INSERT INTO HORNO VALUES (@IDHORNO1,@TIPHORNO,@FECOMPRA) 
			END
END
GO
EXEC USP_INSERT_DATOS 'HO-012','LEÑ','29/09/2023'
GO

--PROC DML 3
CREATE PROC USP_UPDATE_DATOS_CLI
	@ID_CLIEN	CHAR(6), 
	@DNI		CHAR(8), 
	@NOMBRE		VARCHAR(20), 
	@APELLIDOS	VARCHAR(30), 
	@DIRECCION	VARCHAR(45), 
	@TELEFONO	VARCHAR(9)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM CLIENTE AS CLI WHERE CLI.ID_CLIENTE = @ID_CLIEN)
			BEGIN
				PRINT 'CÓDIGO DE CLIENTE INCORRECTO, EL CÓDIGO NO EXISTE'
			END
	ELSE
			BEGIN
				UPDATE CLIENTE SET 
					DNI = @DNI, 
					NOMBRE = @NOMBRE, 
					APELLIDOS = @APELLIDOS, 
					DIRECCION = @DIRECCION, 
					TELEFONO = @TELEFONO
					WHERE ID_CLIENTE = @ID_CLIEN
			END
END
GO
EXEC USP_UPDATE_DATOS_CLI 'CL-015', '77787798', 'ELVER', 'MACANUNCIO MORENO', 'JR. BRIGADA VIRACOCHA', '98888689'
GO

--PROC DML 4
CREATE PROC USP_UPDATE_DATOS_HOR
	@IDHORNO1	CHAR(6),
	@TIPHORNO	VARCHAR(9),
	@FECOMPRA	DATE
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM HORNO AS HOR WHERE HOR.ID_HORNO = @IDHORNO1)
			BEGIN
				PRINT 'CÓDIGO DE HORNO INCORRECTO, EL CÓDIGO NO EXISTE'
			END
	ELSE
			BEGIN
				UPDATE HORNO SET 
				TIPO_HORNO = @TIPHORNO,
				FECHA_COMPRA = @FECOMPRA
					WHERE ID_HORNO = @IDHORNO1
			END
END
GO
EXEC USP_UPDATE_DATOS_HOR 'HO-019','LEÑ','29/09/2023'
GO

--PROC DML 5
CREATE PROC DEL_DATOS_CLI
	@IDCLI	CHAR(6)
AS
BEGIN
	IF NOT EXISTS (SELECT * FROM CLIENTE AS CLI WHERE CLI.ID_CLIENTE = @IDCLI)
			BEGIN
				PRINT 'CÓDIGO DE EMPLEADO INCORRECTO, EL CÓDIGO NO EXISTE'
			END
	ELSE
			BEGIN
				DELETE CLIENTE
					WHERE ID_CLIENTE = @IDCLI 
			END
END
GO
EXEC DEL_DATOS_CLI 'CL-015'
GO
